### ISSUE TITLE
Metadata (tags) changes are not reflected in the editor

### ISSUE THREAD

**Issue by rafasoares** [contentful/ui-extensions-sdk#1071]
I'm building a sidebar extension that updates an entry's tags on input.

I've tried to simply change the returned object from `EntryAPI.getMetadata()`, but it doesn't update the tags in the editor and, therefore, my changes aren't persisted when I save. 

I've tried with the CMA, but then I have to actually save the entry and reload the pages to see the changes. I'd really like to let the editor see the changes in real time and save the entry manually, like I can do with fields (via `FieldAPI.setValue`).

This is my code right now:

```ts
    const metadata = this.entry.getMetadata()
    if (metadata == null) return

    // `tag` here is `TagProps` returned by the CMA via `PlainClientAPI.tags.get`
    // `makeLink` is basically a copy of https://github.com/contentful/contentful-management.js/blob/master/test/utils.ts#L3-L7
    metadata.tags.push(makeLink('Tag', tag)) 
    this.entry.onMetadataChanged(console.log)
```

My suggestion would be to add a `setMetadata` to `EntryAPI`, similar to the `FieldAPI`'s `setValue`. 
Better yet, using getters and setter rather than the Java-like `getX`/`setX` ;)

**Comment by shikaan** [comment]
Hi @rafasoares and thanks for reaching out!

As you have correctly identified, it is currently possible to save metadata of an Entry using the CMA Adapter. 
If you are interested in seeing the changes, we suggest utilizing the [`onMetadataChanged`](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/#receiving-notifications-when-metadata-object-is-changing) method and updating your widget accordingly. 

Unfortunately at the moment the default editor does not react to metadata changes. If you are after that type of reactivity, we recommend building an Entry Editor App and leverage the `onMetadataChanged` as per above.

Hope this helps, feel free to reopen if not.

Best,
Manuel
