### ISSUE TITLE
Forbidden `setValue` update to sibling entry field

### ISSUE THREAD

**Issue by wardpenney** [contentful/ui-extensions-sdk#115]
Hi!

We are working on a custom widget that will be used to update the value of a sibling field on the entry. When we call the SDK's `entry.fields[OUR_FIELD]` we receive the following error:

```
{
  code: "ENTRY UPDATE FAILED",
  message: "Could not update entry field",
  data: {shareJSCodeL "forbidden"}
}
```

The [widget-sdk API docs](https://github.com/contentful/widget-sdk/blob/master/doc/widget-api-frontend.md#entryfieldsid-field) for `.field` mention `field.setValue(value, locale?): Promise<void>` as an endpoint. 

Is there something we are missing?

I see in the docs for the ["using multiple fields" suggested method](https://github.com/contentful/widget-sdk#using-relationships-between-multiple-fields) suggests using the CMA. It would be nice to not have to use the CMA API when we are so close with the widget-sdk API.

Thanks for your help.

**Comment by wardpenney** [comment]
More info:

We are trying to affect a Reference type field, and we are passing it a item result returned from `widget.space.getEntries()`.

CC @pablobm

**Comment by wardpenney** [comment]
Ok, we figured it out!

The payload passed to `setValue` needs to be in the following format for the Reference field:

```
var payload = {
  sys: {
    id: dest.sys.id,
    linkType: 'Entry',
  }
};
```

I will get some time this week and make a PR to docs to make that more clear. Any suggestions on where to affect are welcome!

**Comment by tomasdev** [comment]
@wardpenney how did you make the extension appear in Appearances? `"fieldTypes": ["Link"]` didn't work in my case.
