### ISSUE TITLE
setInvalid not a function

### ISSUE THREAD

**Issue by wardpenney** [contentful/ui-extensions-sdk#116]
Hi all,

It looks like `setInvalid` on `widget.field` is not available. I receive `api.field.setInvalid is not a function` (`api` is the valid sdk Object). 

Is it not yet implemented? If that is the case, mabybe let's remove it out of [the docs](https://github.com/contentful/ui-extensions-sdk/blob/master/doc/widget-api-frontend.md#widgetfield) until we have it. There seem to be other fields within the `field` scope that may also be candidates.

Thanks!

**Comment by geigerzaehler** [comment]
Hi Ward! We recently updated the SDK to version 1.0. Maybe you haven’t updated/rebuild the NPM package. We also renamed it to `contentful-ui-extensions-sdk`.

**Comment by wardpenney** [comment]
Oh yep I was back on the old one. I bet that's it, thanks @geigerzaehler!
