### ISSUE TITLE
SDK hook for when page is done being constructed

### ISSUE THREAD

**Issue by wardpenney** [contentful/ui-extensions-sdk#122]
Occasionally I am getting a `429 Rate Limit Exceeded Error` using the SDK's API. 

**Primary Cause**

Web hooks watching the `onValueChanged` event of other fields are firing many times.

For array-based fields (like Asset field with Multiple, or Reference field with Multiple) it triggers each time an item is added to it during the page's construction. 

For single-value fields (like Reference with Single) it ends up firing one extra time at least, when the item's value is populated into it.

**Solution Suggestions**
- Some sort of a hook from the SDK where I could bind those events, after the page is done being constructed.
- Prevent SDK from dispatching the `onValueChanged` events until the page is done being constructed.
- In the UI Extension, bind the events after a delay (current solution).

Does anyone have any other solution ideas?

Thanks all.

**Comment by zeusdeux** [comment]
This shouldn't really be happening. Could you please provide us a test case that reproduces this behaviour? Ty!

**Comment by jelz** [comment]
You can use `extension.field.onIsDisabledChanged(callback)`. Initially its callback will be called with `true` (editor is disabled because it's loading) and once loaded and the field is not disabled for other reason the callback will be called with `false` (not disabled, ready to do the work).
