### ISSUE TITLE
Unable to set Object field to Object or JSON string

### ISSUE THREAD

**Issue by wardpenney** [contentful/ui-extensions-sdk#124]
Hi!

I am trying to set an Object field type via the `field.setValue()` method in the SDK. I can not seem to give it a value that passes, always returning in a generic error: `code: "ENTRY UPDATE FAILED", message: "Could not update entry field"`. 

These both fail:

```
api.field.setValue({});
```

```
const obj = {};
const objString = JSON.stringify(obj);
api.field.setValue(objString);
```

Am I missing something? I see the two examples, but both of those take the value coming out of CodeMirror plugin. Is there something that CodeMirror is doing that is required?

Thanks

edits: 

* Added call to `field` on API calls
* This is a dumbed-down example, my real life situation has more data in the object. But I wanted to make the example clear with empty JS objects.

**Comment by geigerzaehler** [comment]
We are aware that the error messages do not always provide very helpful information. Usually an update fails because of the following reasons:
* You do not have permission to write the field
* You are passing a wrong type (e.g. a string where the field expects a number)
Can you check the field type (`api.field.type`) and make sure that it is consitent with what you pass to `setValue()`?

**Comment by wardpenney** [comment]
Thanks for replying @geigerzaehler!

Ok so, `api.field.type` returns `"Object"`. So in theory this should work:

```
  const x = api.field.type;
  const obj = {key: 'value'};
  api.field.setValue(obj).then(result => {
    console.log("PASS", result);
  }, error => {
    console.log("FAIL", error);
  });
```

And I get result:

![screen shot 2016-06-29 at 9 59 31 am](https://cloud.githubusercontent.com/assets/615249/16454829/3846ffb2-3de0-11e6-8aa7-cc212b2056ee.png)

**Comment by wardpenney** [comment]
Ok @geigerzaehler we figured it out.

It turns out that we were in some sort of a race condition, trying to `setValue` from within the SDK's `init`. The setting of the `Object` was not a problem when done later (after a user interaction). 

I hope this info helps! In regard to https://github.com/contentful/ui-extensions-sdk/issues/122 it would be great if the `init` was not called until the SDK was fully ready and the Contentful page was finished building. But, that is just a suggestion.

Thanks all

**Comment by zeusdeux** [comment]
Hi @wardpenney! AFAIK, the `init` callback is only called once everything is fully ready. Do you have a minimal test case that we could use to reproduce this issue? 

Thanks!

**Comment by wardpenney** [comment]
@zeusdeux sure! Check out https://github.com/wardpenney/contentful-issue-setvalue-too-soon the instructions are in the `README`.

I found some more information, too. The bug only exhibits if there is a `field.getValue()` request made in the `init` prior to the non-delayed `setValue()`. For some reason, delaying the `setValue()` passes.

**Comment by zeusdeux** [comment]
First off, apologies about the delayed response @wardpenney. We have made a few changes to the sdk that should have resolved your issue. I ran the project you linked above against the latest version of the sdk and did not see the bug manifest itself.

If it does re-occur, feel free to open this issue. Thanks!
