### ISSUE TITLE
Change LocaleSettings for the Entry

### ISSUE THREAD

**Issue by vlsokol-bmi** [contentful/ui-extensions-sdk#1297]
Hi,
Is there a way to change currently focused locale for the entry to another one?
Something similar to ```openBulkEditor``` but without opening a bulk editor, but changing focused locale for the current entry:
```
sdk.navigator.openBulkEditor("id", {
    fieldId: 'id',
    locale: 'de',
    index: 0
  })
```

**Comment by kdamball** [comment]
Hi,

We currently do not offer a way to programmatically change the focused locale in our. We only offer [`sdk.editor.onLocaleSettingsChanged`](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/#receiving-notifications-about-locales-settings-change) which runs on initial local or any user input on focused locale.
