### ISSUE TITLE
Feature Req: Ability to make use of native Asset picker / Link selector in UI Extensions

### ISSUE THREAD

**Issue by nkahoang** [contentful/ui-extensions-sdk#132]
Hi Contentful,

Thank you for the awesome SDK. This is exactly what I've been looking for.

I was wondering if there's an exposed API to invoke the Image/Asset Picker and Link/Reference picker in the form editor? I know that you can use `space.getPublishedAssets` and `space.getPublishedEntries` but it would be much nicer to be able to use Contentful's native pickers.

**Comment by hlabas** [comment]
Hi and thank you for this proposal.

We are currently collecting feedback of this kind to fine-tune the next steps regarding the UI extensions SDK. Allowing more interactions with the web app is indeed part of these steps, although we are not yet at a stage where we can provide with more details on the exact features we will prioritize regarding the assets picker.

We'll keep this thread updated whenever we have more information to share.

Best,
Hervé

**Comment by hlabas** [comment]
Hi!
Just wanted to update this thread to mention that we're actively working on making this happen.
[This PR](https://github.com/contentful/ui-extensions-sdk/pull/145) will be exposing new methods allowing to leverage the existing asset or entry picker.

**Comment by jelz** [comment]
Hi @nkahoang, as of today you can install v3.1.0 of our SDK that contains methods for opening our native selectors. Here's the section in the API reference that describes how to use new methods:

https://github.com/contentful/ui-extensions-sdk/blob/master/docs/ui-extensions-sdk-frontend.md#extensiondialogs

Please let us know what are you thoughts and if it met your expectations. I'll leave this issue opened for couple of days if you've got some immediate feedback.

Best,
Jakub

**Comment by tomasdev** [comment]
I know it's partially related (and technically the original issue is now fixed) but...

There's currently no way of uploading an asset via UI-extension. The Management API method `space.createAssetFromFiles` is not in the ui-extension v3 `extension.space` (probably newer) nor there's a dialog for the asset upload. Can currently only select already-uploaded assets. Is this feature (ability to upload assets via ui-extension) in the roadmap?

**Comment by hlabas** [comment]
Hi Tomas,

Proposing the upload ability from within the asset selection dialog is something we have in our backlog but haven't prioritised yet. This would solve your issue.
I'm keeping tabs on this thread to come back once we do, along with thinking about exposing the upload function in the UI extension SDK.

Best,
Hervé

**Comment by ChristophMueller** [comment]
I would certainly support this feature request.
As of now, is there any workaround for uploading new files directly to contentful from within a UI extension?

**Comment by tomasdev** [comment]
What I ended up using was a custom field JSON and base64 encode the upload. Then you can use the value as your image.

TR.-

**Comment by jelz** [comment]
UI Extensions SDK exposes the default Contentful entity (Entry/Asset) selector with `extension.dialogs` and this is the expected behaviour for this SDK. Teams resposible for the entity selection dialog are aware of this need but there's still no timeline.

Important thing to mention is that UI Extensions automatically get all updates to dialogs. So if direct upload from the selector will be implemented UI Extensions will have it right away.
