### ISSUE TITLE
Passing data to opened dialog app.

### ISSUE THREAD

**Issue by r00dY** [contentful/ui-extensions-sdk#1333]
Hi,

I have an app using two locations: field and dialog. Field location has a button that opens a dialog.

When I use `dialogs.openCurrentApp` I can easily pass parameters from my field location, it works great. But what if, while dialog is opened, I want to notify it about some change? In my case I use `onValueChanged` in my field location (it's only available there via `FieldAPI`). When `onValueChanged` is called I want to send information to currently opened dialog that underlying value changed.

Can I do it with current API?

**Comment by kdamball** [comment]
Hi @r00dY, dialogs we designed to rely on static data. However, I can see why some cases where you might need dynamic updates. For now, I would recommend using `window.postMessage` from the field and reacting to it in your dialog component code. 

Additionally, we are working on a feature that would make this easier but I cannot promise on delivery dates.
