### ISSUE TITLE
Long text isn't searchable through dialogs when the content is an url

### ISSUE THREAD

**Issue by valkko** [contentful/ui-extensions-sdk#146]
I'm using dialogs.selectSingleEntry() to search for an entry. One of the content types used is basically a link, with a title and a long text field (which should be searchable) used as an url, with url validation, However, when typing parts of the url in the search field, no results pop up. Long text fields from other entries containing plain text are searched correctly.
Even when typing the full URL, the search isn't working correctly, it behaves as if the search field is empty, showing all the entries with the specified content types.

**Comment by geigerzaehler** [comment]
In order to reproduce this could you please post the parameters to the `dialogs.selectSingleEntry()` call and also the payload of the content type, including its field definitions?

**Comment by jelz** [comment]
Entry selector was rewritten since then and I believe this issue is gone.
