### ISSUE TITLE
Further explain content management extensions 

### ISSUE THREAD

**Issue by gaapt** [contentful/ui-extensions-sdk#149]
https://github.com/contentful/ui-extensions-sdk/tree/855cdbdca2e5a836035260ba45d78cbab34c5498#content-management-extensions 

It's not clear how such taxonomy ("content management extensions") differs from content editing extensions and what properties are particularly associated with it.

**Comment by sebbean** [comment]
also not sure how or what to do with that info there

**Comment by PepperTeasdale** [comment]
Hey, I know this issue has been here a while and a recent search is not revealing any docs in this area. Can anyone point to a good starting place for this?

**Comment by PepperTeasdale** [comment]
Actually just found this example here: https://github.com/contentful/extensions/tree/master/samples/inbound-references
I notice there are two repos: `extensions` and `ui-extensions-sdk`. It would be helpful to add a reference to the extensions repo in the README to this repo. Will furnish a PR if the maintainers thinks it would be helpful.

**Comment by floelhoeffel** [comment]
I am currently refactoring some the readmes and will incorporate this feedback. Thanks!

**Comment by techpeace** [comment]
Here's a [more current example](https://github.com/contentful/extensions/tree/master/samples/build-netlify) from the `extensions` repo.

**Comment by floelhoeffel** [comment]
Fixed in
