### ISSUE TITLE
Visual: cf-is-loading on disabled button

### ISSUE THREAD

**Issue by tomasdev** [contentful/ui-extensions-sdk#150]
Certain actions require to show a loading indicator while not letting the button be clicked again.
```html
<button class="cf-btn-secondary cf-is-loading" disabled="">Loading</button>
```
Having such a button, loses the disabled styles (opacity 0.4) when that should win in priority over the loading wheel addition.

This is explicitly put in https://github.com/contentful/ui-extensions-sdk/blob/master/lib/style/buttons.styl#L99 but the user case should be valid to have it half opacity.

**Comment by jelz** [comment]
Please use our design system, Forma-36: https://f36.contentful.com/

Legacy styles are won't be supported anymore.
