### ISSUE TITLE
Unable to create/update my extension

### ISSUE THREAD

**Issue by soliveira-nascent** [contentful/ui-extensions-sdk#152]
I'm having the same issue as mentioned here: #130

When executing `contentful-extension create --space-id <space-id>` 

I get the following error:

`Failed to create the extension: TypeError: Cannot read property 'id' of undefined` 

I get the same error when trying to update an extension. Is there another release happening that's causing this error?

**Comment by tomasdev** [comment]
I'm having the same issue.

**Comment by tomasdev** [comment]
More information: this issue doesn't happen when pushing with explicit `--src` (versus using the json with a srcdoc)

**Comment by floelhoeffel** [comment]
Could you share the exact command you are running? Please also verify you have a valid srcdoc and `extensions.json` in the current folder.

**Comment by soliveira-nascent** [comment]
Here's the directory I'm running from and the dist directory (which includes the srcdoc file). The last two commands are the commands I run to try and create this extension.


For more information: Originally this extension was uploaded and I was trying to update but getting the same error, so I deleted it and tried to re-create it but it did not work.


Other extensions which we did not change also get the same error now when we try to update


[cid:5e4f50b1-fb3a-467e-a48e-5e1a19a3051f]


________________________________

**Comment by soliveira-nascent** [comment]
Here's the directory I'm running from and the dist directory (which includes the srcdoc file). The last two commands are the commands I run to try and create this extension.

`ls -la`

```
-rwxr-xr-x    1 steve  staff    572 24 Jul 14:41 README.md
drwxr-xr-x    7 steve  staff    238 25 Jul 11:17 dist
-rwxr-xr-x    1 steve  staff    154 24 Jul 15:55 extension.json
-rwxr-xr-x    1 steve  staff   1680 24 Jul 14:41 gulpfile.js
drwxr-xr-x  493 steve  staff  16762 24 Jul 15:53 node_modules
-rwxr-xr-x    1 steve  staff    499 21 Jul 12:49 package.json
drwxr-xr-x    5 steve  staff    170 26 Jul 16:56 src
```

`ls -la ./dist`

```
-rwxr-xr-x  1 steve  staff    333 25 Jul 11:21 index.html
-rwxr-xr-x  1 steve  staff  45524 25 Jul 11:21 index.min.html
drwxr-xr-x  4 steve  staff    136 24 Jul 15:53 lib
-rwxr-xr-x  1 steve  staff     31 25 Jul 11:21 offer-details-validation.css
-rwxr-xr-x  1 steve  staff   7782 25 Jul 11:21 offer-details-validation.js
```

Command to create the extension:

`contentful-extension create --space-id 9i5l671xsr4y`

I've also tried this:

`contentful-extension create --force --space-id 9i5l671xsr4y`

For more information: Originally this extension was uploaded and I was trying to update but getting the same error, so I deleted it and tried to re-create it but it did not work.

Other extensions which we did not change also get the same error now when we try to update

**Comment by tomasdev** [comment]
Likewise. At first we thought it was an issue on our side. Reverted all changes to last pushed version and that still has the problem. 

TR.-

**Comment by floelhoeffel** [comment]
Just to doublecheck - your issue is with the CLI (https://github.com/contentful/contentful-extension-cli) not the sdk, right?

**Comment by tomasdev** [comment]
Technically you are right.

At the same time the issue is not the CLI itself, since it hasn't been updated in a while, but rather one of the dependencies of it.

**Comment by madtrick** [comment]
@soliveira-nascent hi. We've made some changes to our infrastructure and you should be able to create extensions again. Could you try?

**Comment by tomasdev** [comment]
@madtrick perfect! It worked again.

**Comment by madtrick** [comment]
@tomasdev great to hear! And sorry for the incoveniences
