### ISSUE TITLE
`extension.space.createEntry` documentation seems to differ from actual behavior.

### ISSUE THREAD

**Issue by fleischie** [contentful/ui-extensions-sdk#154]
Hey Contentful Team, 👋

The documentation states, that `extension.space.createEntry(data)` should be of the following form (as I understand it):

```javascript
const data = {
  sys: {
    contentType: <contentTypeId>,
  },
  fields: {
    name: { [locale]: <nameContent> },
    more: [ [locale]: <moreContent> },
  },
}

extension.space.createEntry(data).then(...).catch(...);
```

when I run the command I get the error message "Missing object", similar to [issue #97 on `contentful-mangement.js`].

But passing the content type as the first argument seems to work like it should (and as it is on the management library):
```javascript
const data = {
  fields: {
    name: { [locale]: <nameContent> },
    more: [ [locale]: <moreContent> },
  },
}

extension.space.createEntry(<contentTypeId>, data).then(...).catch(...);
```

I am using version 3 of the library from [unpkg link].

Now I just wanted to clarify:
- Was it a misunderstanding on my side?
- Are the docs outdated/referencing a different version than I am using?
- Anything I otherwise have to consider?

[issue #97 on `contentful-mangement.js`]: https://github.com/contentful/contentful-management.js/issues/97
[unpkg link]: https://unpkg.com/contentful-ui-extensions-sdk@3

**Comment by jelz** [comment]
Closing, it's clear in the docs now: https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#space
