### ISSUE TITLE
Feature: scroll parent page

### ISSUE THREAD

**Issue by tomasdev** [contentful/ui-extensions-sdk#158]
In certain cases, it is useful to be able to scroll the parent page to a specific place.
Example usability case: having `<a href="#point">modify them below</a>` and `<div id="point"></div>` somewhere down below in a rather large custom field.

Technically, it would be scrolling `<div ui-on-scroll="scroll-editor" ui-set-scroll="initialEditorScroll" class="workbench-main__content">`

Do you think this is worth PRing ?

**Comment by geigerzaehler** [comment]
Thanks for the input @tomasdev. We’ll put this feature request into our backlog.

> Technically, it would be scrolling <div ui-on-scroll="scroll-editor" ui-set-scroll="initialEditorScroll" class="workbench-main__content">

I’m not sure what you mean by that. Could you elaborate? If you could make a PR that would be great.

**Comment by tomasdev** [comment]
Where's the repo for the "other side" of the channel connection? or is that private?

`Technically, it would be scrolling` I mean a way for anchors to scroll down on the container page to the proper div, given the default browser behavior.

By the way, I think this doesn't need to be done. It works out of the box when the extension is HOSTED and not on Contentful inline HTML.
