### ISSUE TITLE
Allow for extension to provide help text and settings

### ISSUE THREAD

**Issue by lukasoppermann** [contentful/ui-extensions-sdk#159]
Is there a way to allow the user to insert a custom help text like with other fields?

Also can this be used to have the user create settings, e.g. default values, etc?

**Comment by DanweDE** [comment]
This is currently not possible. Help text of built-in UI components is implemented as a setting. Custom settings for custom UI Extensions would be a new feature. We are aware that this could be useful but we are not currently working on this.

**Comment by lukasoppermann** [comment]
Hey, thanks for the reply. However that is sad to hear, I guess currently not working on it means it is also not on the roadmap at all, right?

**Comment by lukasoppermann** [comment]
I created a new content type `config` now which only has a `configuration` and `value` field. I can retrieve it like this (you might want to create names differently).

```js
            let config = extension.space.getEntries({
              'content_type': 'configuration',
              'fields.configuration': `configuration_${items[0].sys.contentType.sys.id}`
            })
```

Anyway, this works as a hacky workaround, but is definitely not nice.

**Comment by DanweDE** [comment]
Unfortunately, it is at least not on our short term road map for the next couple of months. Of course this could always change and we would inform you on this issue. Nice workaround by the way 👍

**Comment by lukasoppermann** [comment]
Thanks for the info.

**Comment by floelhoeffel** [comment]
@lukasoppermann we are working on a prototype for configuration of UI Extensions - would you be interested in giving us some feedback on a prototype in 2-3 weeks?

Thanks!

**Comment by lukasoppermann** [comment]
@floelhoeffel definitely. 😁

**Comment by stefanjudis** [comment]
@lukasoppermann 

Btw, we shipped extensions parameters. :)

https://github.com/contentful/ui-extensions-sdk/blob/master/docs/ui-extensions-sdk-frontend.md#extensionparameters

**Comment by lukasoppermann** [comment]
So does this close this ticket?

**Comment by stefanjudis** [comment]
I would say so. :) Closing for now, let's reopen in case it's not helping your case. :)

**Comment by abohannon** [comment]
I know this has been closed for 2 years, but was this supposed to provide a field in the "Appearance" tab like the other default fields? For me it seems you need to hard code the help text on the `instance` property. Would be great to take advantage of the "Help Text" field like the default fields so I don't have to clutter my space with a bunch of generic Switch fields that need their own unique helper text.

Or, what would perhaps be better than this, is to just provide the Switch toggle as a default field option.
