### ISSUE TITLE
Feature req: allow confirm modals

### ISSUE THREAD

**Issue by PepperTeasdale** [contentful/ui-extensions-sdk#162]
This would entail updating the iframe sandbox attribute to include `allow-modals`. We have a button in the sidebar that triggers a webhook. We'd like our editors to confirm before triggering. We can add confirm buttons underneath of course, but for various reasons, an actual confirm box would be preferrable.

**Comment by floelhoeffel** [comment]
That is an interesting usecase, thanks for the feedback. We are also thinking about doing something around notifications from extensions. I'll add it to our feedback pool, thanks!

**Comment by kiliansch** [comment]
Another use case is CKEditor, which uses modals for inserting URLs or images. They work fine, but trigger a confirm() which is being supressed. I have a workaround using the ui-extensions-sdk dialogs:

```javascript
var origConfirm = confirm;
confirm = function(message) {
    extension.dialogs.openAlert({
        title: 'Confirm changes',
        message: message,
        confirmLabel: 'Ja!',
        cancelLabel: 'Nein.'
    }).then(result => {
      return result;
    });
};
var origAlert = alert;
alert = function(message) {
    extension.dialogs.openAlert({
        title: 'Hinweis',
        message: message
    }).then(result => {
        return result;
    });
};
```

**Comment by floelhoeffel** [comment]
Yes - we added support for our native dialogues to the SDK in v3.5.

See: https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#opening-a-confirm-dialog


@kiliansch any chance you plan to open source your extension? Curious to see what it does!

**Comment by kiliansch** [comment]
There's not much to share, it's only CKEditor 4 with the adjustment of `confirm` and `alert` seen above :)
