### ISSUE TITLE
`extension.entry.fields[field].setValue(value, locale)` updates entry, but UI doesn't update

### ISSUE THREAD

**Issue by cachrisman** [contentful/ui-extensions-sdk#166]
I'm working on an [extension](https://github.com/cachrisman/locale_publishing_extension) and it makes a call 
```javascript
// field = 'title', locale = 'en-AU', and value = 'I am a title'
extension.entry.fields[field].setValue(value, locale)
```
and the entry is updated on the API, but the webapp UI doesn't update. Anything I can do to get the UI to update correctly?

**Comment by floelhoeffel** [comment]
@cachrisman you mean in the actual UI Extension that sets the field value?

If you send a new value to the API the UI extension needs to take care of reflecting the change visually. The best practice is to listen for 

https://github.com/contentful/ui-extensions-sdk/blob/master/docs/ui-extensions-sdk-frontend.md#extensionfieldonvaluechangedcb-function

That handler triggers for every value change the API is aware of.

**Comment by nerdess** [comment]
@floelhoeffel the docs seem to have moved, can you point to the new docs? I have the same issue but are struggeling to find the solution you have referenced.

**Comment by vctrivas** [comment]
Seeing an issue when expecting `field.onValueChanged` to be triggered when using a different locale than the `fallback` on `setValue`.

Here a simplified example:

With fallback `en-US` locale:
```javascript
field.onValueChanged('en-US', () => {console.log('updated')}) // works as expected
field.setValue('some value', 'en-US')
```
With `es` as locale:
```javascript
field.onValueChanged('es', () => {console.log('updated')}) // will not be triggered
field.setValue('some value', 'es')
```
You can see here when the locale is set to a different locale than the fallback the `onValueChanged` will not be triggered.

Any suggestions?
