### ISSUE TITLE
Import when bundling with Webpack/Babel

### ISSUE THREAD

**Issue by backflip** [contentful/ui-extensions-sdk#169]
Since [`api/index.js`](https://github.com/contentful/ui-extensions-sdk/blob/master/lib/api/index.js) is exporting `var init`, I had to use `import * as contentfulExtension from 'contentful-ui-extensions-sdk'` rather than `import contentfulExtension from 'contentful-ui-extensions-sdk'`. The latter returned `undefined`.

**Comment by sebbean** [comment]
same issue here

**Comment by jelz** [comment]
We decided not to modify exports of v3. The current state is now better documented: https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#initialization

Exports will be reorganized and the default export will be introduced in v4 of the SDK.
