### ISSUE TITLE
Set entry fields to hide/show

### ISSUE THREAD

**Issue by sami616** [contentful/ui-extensions-sdk#178]
Is it possible to hide/show other fields that belong to the content type using ui extensions ? Also, is conditional field rendering on the road map to ever become a built in feature?

**Comment by jelz** [comment]
This feature request was qualified for development and is now in our backlog, we cannot commit on any target date unfortunately.

**Comment by lundmikkel** [comment]
What is the status on conditional field rendering? That is, the value of one field should hide/show other fields. It seems to be somewhat possible to do with [UI extensions](https://www.contentful.com/developers/docs/tutorials/general/uiextensions-entry/), but that requires you to write you own UI, which isn't very attractive.

**Comment by sami616** [comment]
Would love to see this feature land soon

**Comment by kik-o** [comment]
Any word on this feature, or if it's still in flight even? 👀

**Comment by jariExxeta** [comment]
+1 for this feature

**Comment by brokelyn** [comment]
this contentful extension can be used as workaround for now until it gets a native feature 

https://www.contentful.com/marketplace/app/conditional-fields-by-prototyp/

**Comment by dlitricotlg** [comment]
Hello, any news on this feature?

**Comment by lundmikkel** [comment]
@jelz Are you still not committing on any target date?

**Comment by jelz** [comment]
@lundmikkel I'm not with Contentful for 3 years now; I think there's a chance that creating a new issue for that could put it back on the radar given lots of thumbs up here

**Comment by sami616** [comment]
I got tired of waiting. I ended up writing my own extension that allows conditionally hiding fields as well as /grouping of fields into collapsible responsive grids that can also be optionally hidden.
