### ISSUE TITLE
Allow for more dynamic extension customisation by user

### ISSUE THREAD

**Issue by lukasoppermann** [contentful/ui-extensions-sdk#181]
Hey, it would be neat if the user could customise extensions more (easily).

For example if you have an editor for objects like https://github.com/lukasoppermann/contentful-key-value-editor it would be neat to allow the user to add fields or configure individual fields.

As a workaround I now have a field and the user can add `csv`s to have a dropdown instead of an input. With `Label:value` syntax, but it feels a bit hacky.

**Comment by floelhoeffel** [comment]
Hey Lukas,

Thanks for the input! Could you elaborate a bit more on the type of configuration you would like to see? When would that configuration be provided to the extension?

Thanks

**Comment by lukasoppermann** [comment]
Hey Frederik,

sure I can try. So currently I can define have the user fill in a text field, set a boolean or select from an enum.

However, something like the tags input is not available. It is also not possible to build something where the user adds more fields. For e.g. you have an object with fields, you can not easily let the user define how the object looks.

A product might have a "product id", a "name" and a "price", while meta tags might only have "tag name" (maybe even as a dropdown) and "tag value". Allowing this in the configuration would be great.

**Comment by jelz** [comment]
This feature request was qualified for development and is now in our backlog, we cannot commit on any target date unfortunately.
