### ISSUE TITLE
Navigator callback event

### ISSUE THREAD

**Issue by JorgeLGonzalez** [contentful/ui-extensions-sdk#191]
What's the best way for a custom extension app to get notified when a navigator slide-in dialog closes? The docs state that navigator.openEntry (for example) returns a promise that resolves when the dialog opens, but I'm looking for something that tells me when the dialog closes so that my code knows the entry in question may have changed and an update may be needed.

**Comment by suevalov** [comment]
Hi @JorgeLGonzalez,

Thanks for the question! There is no convenient way to receive close notification, but this issue is at the top of our backlog and we hope to add this method soon. Keep posted!

**Comment by bezoerb** [comment]
Are there already any updates on this one? Is there a possibility to open up a PR to fix this?
/cc @jelz @suevalov

**Comment by thejawker** [comment]
What is the current status on this one? Thansk!

**Comment by ericfennis** [comment]
Any news on this one? Or a work around?

We're working on a custom entry with conditional assets fields, but we're are stuck with receiving changes when an assets is changed.

We tried to use the onValueChange event, but that not working for assets. Only the change will be fired when an id is changed.

**Comment by suevalov** [comment]
Going to be released soon in `3.10.3`

**Comment by suevalov** [comment]
Release in `3.10.3`.

For details: https://github.com/contentful/ui-extensions-sdk/pull/259/commits/a587f9cb5771c9a8022ef48418fa352444ba5aed

**Comment by joeweale** [comment]
Sorry to reopen, this seems to work fine until an entry is deleted and then it seems the promise is never resolved?
