### ISSUE TITLE
Add `getEditorInterface` method to `spaceMethods`

### ISSUE THREAD

**Issue by visualfanatic** [contentful/ui-extensions-sdk#198]
Could you add `getEditorInterface` method to the `spaceMethods` array?
https://github.com/contentful/ui-extensions-sdk/blob/9c3f512b3197467a49eae4e1c4356f5274848bc2/lib/space.js#L1

This could be really useful for many extensions that for example need access to field's help text or boolean labels (in case if they are custom).

**Comment by suevalov** [comment]
@visualfanatic The method was added to SDK and available starting `3.8.0`
