### ISSUE TITLE
Improvement: Environment information should be more clear in the SDK

### ISSUE THREAD

**Issue by rawbert** [contentful/ui-extensions-sdk#201]
I needed to know what environment my ui extension was executing in. Couldn't find anything in the official docs. Eventually I found that environment information was located in `sdk.contentType.sys.environment.sys.id`.

A more natural location for this info would be sdk.space or maybe sdk.environment.

**Comment by suevalov** [comment]
@rawbert 

We've just released `ui-extensions-sdk@3.8.0` with a new `sdk.ids` object which consists all useful ids that you might need in your extension.

```
sdk.ids.extension
sdk.ids.user
sdk.ids.space
sdk.ids. environment
// etc
```
