### ISSUE TITLE
UI-Extension not working in standalone javascript file!!!

### ISSUE THREAD

**Issue by mjubil1** [contentful/ui-extensions-sdk#203]
I been following the UI Extension tutorial in Contentful and ran into an issue using npm start. When I start the server nothing displays to the browser. Even trying to log to the console in the javascript file nothing shows, but it tends to work when I place the code in the Index.html script tags. 

Can someone explain what I am doing wrong?

**Comment by suevalov** [comment]
Hello @mjubil1! Are you using `create-contentful-extension`, right? 

Do you follow this instruction: https://github.com/contentful/create-contentful-extension#creating-an-extension? 

There's a nice video that demonstrates the whole development flow. You can find it here: https://www.contentful.com/developers/docs/extensibility/ui-extensions/managing-a-ui-extension/
