### ISSUE TITLE
Extensions have no access to their own extension ID

### ISSUE THREAD

**Issue by seibert-io** [contentful/ui-extensions-sdk#206]
If a field extension, I am trying to open this very extension via `dialogs.openExtension`. The extension itself detects by its parameters whether it is executed in a dialog. 
`dialogs.openExtension` requires the id of the extension to open being specified. However, when installed via Github, extensions are given a random id and the id from `extension.json` is ignored, rendering the extension incapable of knowing it's own ID. 

As one potential approach to a solution, `BaseExtensionSDK` could be augmented with an id: string property, conveying the current extension's ID. This way it would be available to all extensions in the init methods.

**Comment by suevalov** [comment]
@seibert-io We've just released `ui-extensions-sdk@3.8.0` with a new `sdk.ids` object which consists all useful ids that you might need in your extension.

```
sdk.ids.extension
sdk.ids.user
sdk.ids.space
```
