### ISSUE TITLE
Add "Open Bulk Editor" to the Navigator

### ISSUE THREAD

**Issue by 0xStarcat** [contentful/ui-extensions-sdk#250]
Hi! Are there any plans to extend the `Navigator` to allow us to open the new `Bulk Editor` that's currently available for `multi-reference` fields? 

I think this would be very useful because my team likes this editor and our models depend on lots of `multi-reference` fields. Adding this to the UI extension SDK would make our extensions even better. 

Thank you!

https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#navigator

https://www.contentful.com/blog/2017/02/13/product-improvements-shipped-in-nov-dec-jan/

**Comment by suevalov** [comment]
Hi @0xStarcat! Thanks for a feature request, we're definitely looking at it and it most likely to be implemented by end of January.

**Comment by suevalov** [comment]
@0xStarcat released in 3.12.0
