### ISSUE TITLE
Help with `sdk.window.startAutoResizer() `

### ISSUE THREAD

**Issue by siffogh** [contentful/ui-extensions-sdk#252]
I created a UI extension where you can click a dropdown and add entries.

I noticed that sdk.window.startAutoResizer() doesn’t always work properly:

A lot of times, when adding a new entry, the iframe’s height doesn’t change, which hides some of the content.
When opening the dropdown, I have change the body’s minHeight manually to adapt to the height of the dropdown.
Do you have any tips to handle these issues? Would really appreciate some help here.

**Comment by suevalov** [comment]
@siffogh If your dropdown element is using an absolute positioning then you might get wrong autorisize results. I suggest to use `sdk.window.updateHeight` manually on dropdown menu toggle.
