### ISSUE TITLE
Add publishing schedule to entry

### ISSUE THREAD

**Issue by westmark** [contentful/ui-extensions-sdk#265]
Hi! 

It would be tremendously useful to be able to access the publishing schedule of an entry. Read-only is fine. I guess this could be included in the result from `entry.getSys()` perhaps?

Or is this already available somewhere?

**Comment by suevalov** [comment]
Hi @westmark ! The new methods will be available soon in `3.11.0`

**Comment by westmark** [comment]
@suevalov I'm trying to use the new methods:

```
try {
      const schedule = await sdk.space.getEntityScheduledActions('Entry', id);
      schedules.push(schedule);
    } catch (error) {
      console.error(error);
    }
```

But all I'm getting are thrown errors. I can't even see a request being made over the network

```
code: "Error"
message: "Request failed."
data: undefined
```

Using `3.11.2`

**Comment by westmark** [comment]
Never mind, tried again now (without changing anything) and it worked. I assume the methods weren't properly exposed by the parent window earlier.
