### ISSUE TITLE
Extension id being ignored.

### ISSUE THREAD

**Issue by PhuTran92** [contentful/ui-extensions-sdk#267]
Hi guys,

I am trying to open an extension by called `dialogs.openExtension`. However, when I installed it via my hosted-server, extensions are given a random id and the id from `extension.json` is ignored. Is there a way that I can persist the extension id or retrieve it by extension name? 

Thanks.

**Comment by pixelass** [comment]
@PhuTran92 how did you solve this issue?

**Comment by christopher-theagen** [comment]
> @PhuTran92 how did you solve this issue?

https://github.com/contentful/ui-extensions-sdk/issues/206

**Comment by pixelass** [comment]
@christopher-theagen  Thank you for the link.
We actually use this:

`contentful extension create --id foo --name "Foo Bar" --field-types Symbol --src https://mywebsite/foo-bar/`

**Comment by christopher-theagen** [comment]
@pixelass Welcome! Solid usage of the CLI
