### ISSUE TITLE
Feature req: On outside interaction callback

### ISSUE THREAD

**Issue by westmark** [contentful/ui-extensions-sdk#288]
Hey! I am using the Dropdown component from forma-36. This component has a `onClose` prop which is supposed to close the dropdown when the user interacts with something else on the page. While this works fine in the the context of the extension's iframe, it does not work when the user interacts with something outside of it.

One way to solve this would be to have some kind of mechanism in the sdk for receiving events when the user interacts outside the iframe. The details of this interaction are of course not relevant - just need to get a notice.

**Comment by davidfateh** [comment]
Hi @westmark,

You could try listening for the `blur` event on your iframe's `window` object to call necessary code when the user interacts with elements outside of your iframe.

```js

window.addEventListener('blur', (event) => {
  onClose();
});
```

Let me know if that works for you.

**Comment by westmark** [comment]
Tried this a while back (it worked) but forgot to close the issue! :)
