### ISSUE TITLE
navigator.openPageExtension not having an effect

### ISSUE THREAD

**Issue by backflip** [contentful/ui-extensions-sdk#293]
Using `navigator.openPageExtension` does not have an effect in my extension. The code runs but there is no action. Both with and without the `{ id: EXTENSION_ID }` param.

Possibly relevant:
- Self-hosted on `https://localhost:3000`
- Displayed as `Legacy sidebar extension`

The same problem is occurring when attempting to open the extension from an app displayed in the sidebar, nothing happens on `navigator.openPageExtension({ id: EXTENSION_ID })`.

Is this a known limitation? Or could I provide any additional debugging information?

**Comment by DaniRey** [comment]
As @backflip and I work on the same extension I can add the following details.

`navigator.openPageExtension({ id: EXTENSION_ID })` works if it is in the Sidebar of and Extension, but not a `Legacy sidebar extension`.

The same code does not work, when part of an App.

**Comment by backflip** [comment]
We were able to use the new `openCurrentAppPage` inside of an app, so I guess this is only an issue when using a legacy sidebar extension.

**Comment by davidfateh** [comment]
Hey, I recently made changes to this area of the code so I'd like to thank you for bringing this to my attention. As we try and move more of our ideas into apps, we suggest that you use the new method `openCurrentAppPage` like you've already done.

For now, that method will only allow you to navigate to the same app or extension from whence the call originates.

Let me know if you run into any more problems.
