### ISSUE TITLE
slideIn option for openEntry not working on LOCATION_PAGE

### ISSUE THREAD

**Issue by backflip** [contentful/ui-extensions-sdk#298]
Adding `{ slideIn: true }` to `openEntry` results in nothing happening at all when triggered on an app page.

It would be great to be able to use the slide-in editor on app pages, too.

**Comment by davidfateh** [comment]
Hi @backflip,

We definitely agree that being able to do this on the app page would be very helpful. We are currently planning new additions to the developer experience for the App Framework and this is likely one of them!

**Comment by backflip** [comment]
@davidfateh, thanks, looking forward to it!
