### ISSUE TITLE
Extension won't execute SDK API calls in version compare view

### ISSUE THREAD

**Issue by mc-jordan-andree** [contentful/ui-extensions-sdk#312]
I'm working on a bit of code for a UI Extension that fetches the linked entry from a field that references another entry. Its a pretty straight-forward one-to-one relationship.

However, when I load up the Entry version compare view, the extension can't fetch the linked  entry through the SDK. Example code:

```js
sdk.space.getEntry(sdk.field.getValue().sys.id)
  .then(res => console.log(res))
  .catch(err => console.log(err));
```

When loaded, this logs nothing to the console and it seems `getEntry` no-ops. Is it expected that a UI extension would  fail in the compare view or am I missing something? 

Also, here is the extension definition:

```js
module.exports = {
  name: "My Ext",
  srcdoc: "./dist/my-ext/index.html",
  fieldTypes: [
    {
      type: "Link",
      linkType: "Entry"
    }
  ],
  sidebar: false
};
```

**Comment by Jwhiles** [comment]
Hey @mc-jordan-andree I've just tried to reproduce this issue, and was not able to do so. It appears that these methods are working correctly for me. Can you verify that your extension is being rendered in this location? Are other sdk methods working?
