### ISSUE TITLE
navigator.openEntry resolve promise on close

### ISSUE THREAD

**Issue by joeweale** [contentful/ui-extensions-sdk#321]
Hi,

Having trouble with waitForClose on the navigator sdk. It doesnt seem to resolve if the item is deleted but works fine if it's not.

I'd expect it to still resolve but with an empty entry property.

Thanks

Joe

**Comment by Jwhiles** [comment]
Hey Joe, thanks for reporting this issue. I've been able to reproduce the problem, and will record the bug.

**Comment by VaguelySerious** [comment]
Hi Joe, thank you again for bringing this to our attention. `sdk.navigator.openEntry` with `waitForClose` now resolves if the entity is deleted by any user during use of the slide-in editor.
Please refer to the [updated documentation](https://www.contentful.com/developers/docs/extensibility/ui-extensions/sdk-reference/#navigator) as to the exact details.

**Comment by joeweale** [comment]
Thanks all 👍
