### ISSUE TITLE
Detect compare mode for contentful app

### ISSUE THREAD

**Issue by KuznetsovNikita** [contentful/ui-extensions-sdk#326]
### Issue
Hi, I created Contentful app with my own Markdown Editor, with some feature then required by customer.

How I can detect that app will run in compare page?

So that I can display the content in preview mode, in full height.
I don't can find any flags or kinds in code, and I don't can find any documentation about this.

I init my app like this:
```
import { MarkdownEditor, renderMarkdownDialog } from 'field-editor-markdown';

init(sdk => {
  if (sdk.location.is(locations.LOCATION_DIALOG)) {
    render(renderMarkdownDialog(sdk), document.getElementById('root'));
  } else if (sdk.location.is(locations.LOCATION_ENTRY_FIELD)) {
    render(<MarkdownEditor sdk={sdk} />, document.getElementById('root'));
  }
});
```
Thanks.

**Comment by Jwhiles** [comment]
Hey @KuznetsovNikita 

Your app will be rendered in the snapshot comparison view, however there's no way to tell if it's being rendered in that view or in the normal view. However the SDK will be set it in a readonly mode when it's rendered in the snapshot comparison view.

**Comment by KuznetsovNikita** [comment]
@Jwhiles Hi

How I could detect this is a read-only mode?
