### ISSUE TITLE
SDK Init not Resolving for NextJS Local Dev Server

### ISSUE THREAD

**Issue by dtothefp** [contentful/ui-extensions-sdk#344]
This may be more a limitation of NextJS and I've created a discussion there

https://github.com/vercel/next.js/discussions/17725

I see in the SDK source code that the `init` callback is called after a window `'message'` event is fired.

https://github.com/contentful/ui-extensions-sdk/blob/master/lib/channel.ts#L13

For some reason in NextJS local dev server this even is not being fired or is happening before loading of the SDK? If I build static assets and run the prod server everything works as expected. I realize this is probably not an issue of the SDK but any advice you could offer on how to ask the right questions to get this resolved would be helpful.

**Comment by dtothefp** [comment]
I've ended up loading the SDK with a script tag instead of dynamic import because I found that if `init` is called outside of the async no SSR component then it will receive the `postMessage` from the iFrame

```js
let init;

if (process.browser) {
  init = new Promise((res) => window.contentfulExtension.init(res));
}

const DynamicPageMetaExtension = async (): Promise<React.FC> => {
  const {
    default: PageMetaInputUIExtensionLazy,
  }: {
    default: React.FC;
  } = await import(`extensions/field/PageMetaInput`);

  const sdk = await init;

  return (): ReactElement => (
    <ContentfulUIExtensionsContext.Provider value={{ sdk: sdk as FieldExtensionSDK }}>
      <PageMetaInputUIExtensionLazy />
    </ContentfulUIExtensionsContext.Provider>
  );
};
```

**Comment by Jwhiles** [comment]
Hey, 

I'm not totally familiar with next.js - but if I understand your examples, it appears that the `DynamicPageMetaExtension` component is rendered server side. If that is this case then I would expect the `init` function not to be called. 

The init function is intended to delay rendering of your app/extension until the Contentful web app is ready for it, which will never be the case during server side rendering. I assume that the next.js DEV server actually implements server side rendering, which may be what is causing your problem.

**Comment by pixelass** [comment]
We use it like this:

**Hook** 

```tsx
import React from "react";
import {FieldExtensionSDK} from "contentful-ui-extensions-sdk";

export const useContentfulSdk = () => {
    const [contentfulSdk, setContentfulSdk] = React.useState<null | FieldExtensionSDK>(null);
    React.useEffect(() => {
        const run = async () => {
            const {init} = await import("contentful-ui-extensions-sdk");
            init((sdk: FieldExtensionSDK) => {
                setContentfulSdk(sdk)
            });
        }
        run();
    }, [setContentfulSdk]);
    return contentfulSdk;
}
```

**HOC** 

```tsx
import { FieldExtensionSDK } from "contentful-ui-extensions-sdk";
import React from "react";
import { useContentfulSdk } from "../hooks/use-contentful-sdk";
import { Spinner } from "@contentful/forma-36-react-components";

export interface WithSdkProps {
	sdk: FieldExtensionSDK;
}

export const withSdk = (Component: React.ComponentType<WithSdkProps>) => {
	return () => {
		const sdk = useContentfulSdk();
		return sdk ? <Component sdk={sdk} /> : <Spinner size="large" />;
	};
};

```

**Extension** 

```tsx
import { withSdk } from "../../utils/with-sdk";

interface ExtensionProps {
    sdk: FieldExtensionSDK;
}
const MyExtension:React.FC<ExtensionProps> = ({ sdk }) => {
    return <div>only visible on app.contentful.com</div>
}
export default withSdk(MyExtension);

```

**Page**

```tsx
import { NextPage } from "next";
import React from "react";
import MyExtension from "../apps/my-extension";
import Layout from "../components/Layout";

const MyExtensionPage: NextPage = () => {
	return (
		<Layout>
			<MyExtension />
		</Layout>
	);
};

export default MyExtensionPage;

```

**Comment by Jwhiles** [comment]
It looks like that's a good approach. I'm going to close this issue, as it doesn't seem like there are any changes that need to be made. Feel free to re-open this if you think there are improvements we need to make.
