### ISSUE TITLE
Custom content view in 'Insert existing entries' dialog

### ISSUE THREAD

**Issue by DmitroPustovit** [contentful/ui-extensions-sdk#347]
Hello, 

I'm currently discovering the possibility of extension SDK and wondering how I can tweak the view of the content inside of the 'Insert existing entries' dialog (dialog.selectMultipleEntries)? We want to add some additional information from content to this card, it should make much easier selection necessary content.

**Comment by Jwhiles** [comment]
Hey @DmitroPustovit - the extension SDK doesn't allow you to edit the entry picker directly. You would need to instead have you App render a custom entry picker in the Dialog location, and use the `dialogs.openCurrentApp` method to open that dialog when needed.
