### ISSUE TITLE
Failed to fetch published entries exceeding 1000 links

### ISSUE THREAD

**Issue by parakhkunal** [contentful/ui-extensions-sdk#454]
We use a [UI extension](https://github.com/jbendercode/contentful-ui-ext-colour-picker) which uses the extension API to fetch the published entry in question. A few of the entries we've, exceed the technical limitation of 1000 on links set up by Contentful and fail to render the correct values for the fields. Is there any workaround? Any guidance will be appreciated. Thanks in advance!

**Comment by FLoppix** [comment]
Hey @parakhkunal !

Can you elaborate a little bit more? Is the the UI extension not able to render the fields or is the whole Contentful web app not able to render? 

Best,
Felix

**Comment by parakhkunal** [comment]
> Hey @parakhkunal !
> 
> Can you elaborate a little bit more? Is the the UI extension not able to render the fields or is the whole Contentful web app not able to render?
> 
> Best,
> Felix

Hi @FLoppix, thanks for taking time to check this out. The UI extension is not able to render only the field values. All other field values are loaded correctly. Maybe this will help - 
<img width="1597" alt="Screen Shot 2020-12-22 at 10 42 54 PM" src="https://user-images.githubusercontent.com/1094617/102956668-6a558880-448d-11eb-9f1f-0606abbbd92d.png">

**Comment by FLoppix** [comment]
Hey @parakhkunal !
Sorry for not getting back in time. Hope you had relaxing holidays. Unfortunately you hit the technical limit with the amount of links in your entry. You can find our technical limits [here](https://www.contentful.com/developers/docs/technical-limits/). Is there any possibility that you can model your content type in a different way? Having over 1800 links on one entry is a lot.

**Comment by parakhkunal** [comment]
> Hey @parakhkunal !
> Sorry for not getting back in time. Hope you had relaxing holidays. Unfortunately you hit the technical limit with the amount of links in your entry. You can find our technical limits [here](https://www.contentful.com/developers/docs/technical-limits/). Is there any possibility that you can model your content type in a different way? Having over 1800 links on one entry is a lot.

Hi @FLoppix, no issues. Thanks for responding. I got a similar feedback from contentful support as well and looks like there is no other way than re-modeling. We use contentful only as a publishing pipeline and don't use it to fetch entries, so this was never a problem until the extension stopped working for such entries.
