### ISSUE TITLE
Access API method can always returns true

### ISSUE THREAD

**Issue by nekosaur** [contentful/ui-extensions-sdk#487]
I've been trying to figure out how the `sdk.access.can` method works but it seems like whatever I throw at it, it always returns `true`?

I have a regular member assigned to a custom role that only has read access to content, nothing else. All of the following calls return `true` when I am expecting them to return `false`.

```js
sdk.access.can('create', 'ContentType')

sdk.access.can('update', {
  sys: { type: 'Entry', id: 'entry-id' },
  fields: {
    title: { en: 'hello!' },
  },
})

sdk.access.can('create', {
  sys: {
    type: 'Entry',
    contentType: {
      sys: { id: 'content-type-id', type: 'Link', linkType: 'ContentType' },
    },
  },
})
```

I have also tried adding explicit Denied rules such as `Create - Any Entry - Example content type`, but still it returns true when I query if I am allowed to create that example content type.

**Comment by VaguelySerious** [comment]
Hey @nekosaur, we've been unable to reproduce the issue based on the details you mentioned.
Can you share some more information about where you are calling the SDK methods from, and what the custom role looks like?

**Comment by nekosaur** [comment]
I figured out the issue. I had not noticed this disclaimer.

![image](https://user-images.githubusercontent.com/623137/104438510-5e427f80-5590-11eb-801b-b87b07234110.png)

What is the reason for only applying permissions on master environment? We use a `dev` environment for development purposes, so not being able to test out permissions while developing is a big drawback. Of course we can work around it by temporarily switching out a production extension in `master` for the development version, but that's not an ideal solution, and pretty cumbersome in the long run.

**Comment by VaguelySerious** [comment]
Thank you for raising this issue. We are aware that this limitation might complicate the development flow in certain scenarios, which is why we are considering changing this in the future.
Until any definitive decisions is made, however, I'm sorry to inform you that it's not possible to use content level permissions in environments other than `master`.
