### ISSUE TITLE
Popups cut off by iframe

### ISSUE THREAD

**Issue by BraunreutherA** [contentful/ui-extensions-sdk#532]
Hi Contentful team, 

I'm using the reference editor field from the official contentful field editors repository. As Field Editors in contentful apps are rendere by iframes the popups are cut off (see attached image). 
I think this is a problem for everybody using custom reference editor fields. Do you have an official solution for the problem? I'm not realy happy to expand the height of the field so I can show the whole popup. 

<img width="301" alt="Screenshot 2021-02-07 at 12 47 25" src="https://user-images.githubusercontent.com/9135543/107145593-fd198c00-6942-11eb-98f4-ca740c8d5c3e.png">

**Comment by shikaan** [comment]
Hi @BraunreutherA and thanks for reaching out!

As you can check by yourself inspecting the page, UI Extensions run in an `<iframe>`. Therefore, the dropdown in the picture is unable to be rendered in the `top` frame, outside of the `<iframe>` itself.  

So, back to your question, there is unfortunately no other way than updating the height of the widget as you have correctly suggested.

**Comment by BraunreutherA** [comment]
Hi @shikaan, 

already thought that would be the case. I'll try to find another solution then. Also as a hint for the contentful apps: You could make the iframes slightly bigger, than the native field-editors. That way a dev can give a little padding to make them appear in the same size and display at least the focus ring properly.

**Comment by shikaan** [comment]
Hi @BraunreutherA and thanks for the suggestion!

The App Framework itself is much wider in scope than the Field Editors, so we don't know upfront what the user decides to render and thus it's unfeasible for us to set the height you would expect in advance. This is the reason why we provide utility methods to, for example, set height.

I am now closing this issue, as the question above has been answered. Feel free to open it again should you have more questions.
