### ISSUE TITLE
Unknown method "getEntries"

### ISSUE THREAD

**Issue by nenadg** [contentful/ui-extensions-sdk#657]
Hi, 

I'm currently facing an issue with custom Contentful UI component that consumes extension API. Simple query with `getEntries` returns error, test script is something like this:

```
cfExt.init(function (api) {
      // Whenever the size of this document changes we adjust the size of
      // the IFrame in the Contentful App.
      api.window.startAutoResizer();
      cfApi = api;

      const currentItemId = api.entry.getSys().id;

      api.space.getEntries({
          'links_to_entry': currentItemId
      })
      .then((entries) => {
        console.log('linked to:', entries)
      });
  });
```

Error returned, looks like this:
![Screenshot from 2021-04-20 15-28-14](https://user-images.githubusercontent.com/1519100/115403830-0fd6f980-a1ed-11eb-921f-00f1efd2d539.png)

Any help with this would be more than great :).

**Comment by jelz** [comment]
@nenadg - can you check now? We've just shipped a fix

**Comment by nenadg** [comment]
Yeah, it works :) Thanks, this was fast
