### ISSUE TITLE
navigator.openCurrentAppPage({path}) Consistently Throwing Error

### ISSUE THREAD

**Issue by hansef** [contentful/ui-extensions-sdk#766]
We have an app which we're serving from localhost (in development) and S3 (production) and we're consistently seeing the same behavior on both installs.

We've got a hook which looks like this for link actions:

```
import React from 'react';
import { ContentfulSDK, ContentfulSDKProps } from 'context/ContentfulSDK';
import { useHistory } from 'react-router';

export function useNav(path: string) {
  const { pageSDK }: ContentfulSDKProps = React.useContext(ContentfulSDK);
  const history = useHistory();

  const handleLink = React.useCallback(
    (e) => {
      if (!e.ctrlKey) {
        e.preventDefault();
        pageSDK?.navigator.openCurrentAppPage({ path });
        history.push(path);
      }
    },
    [history, path, pageSDK]
  );
  return handleLink;
}
```

The call to `navigator.openCurrentAppPage({ path })` is consistently throwing this error:

```
Uncaught (in promise) {code: "Error", message: "Cannot navigate between different widget types!", data: undefined}
```

... even though the URLs we're providing to it are relative to the current app. Still seeing this problem if we provide full URLs as well, aka both:

* `/contentItems` and
* `https://app.contentful.com/spaces/gcwac57vok7r/apps/app_installations/4MGVNU2RpXFfDehBt8MfDr/contentItems`

... throw the same error.

We're also getting this error even with a simple `pageSDK?.navigator.openCurrentAppPage()` (aka no path provided, should just take you to the app root).

**Comment by kdamball** [comment]
There was an SDK error and should be fixed now.
