### ISSUE TITLE
space.getUsers() doesnt return all of users

### ISSUE THREAD

**Issue by mlawingco** [contentful/ui-extensions-sdk#889]
Hi, Contentful team

I run into problem with `space.getUsers()` which doesn't return all of the users

Here is a gist code 
```javscript
        const getUsers = await sdk.space.getUsers();
        const sys = await sdk.entry.getSys();
        const creatorData = getUsers.items.find(
            (data: any) => data.sys.id === sys.createdBy.sys.id
        );
```
We have a 80+ users on our space but this getUsers only returns 25 items, making our sidebar extension work inconsistently

Here is what it returns

![image](https://user-images.githubusercontent.com/62869210/127261043-4811f4ff-2892-4274-9932-32ae0e74cfca.png)

It only gets 25 because its the limit. 

Tried

- `getUsers(100)`
- `getUsers(0, 100) // skip, limit similar to readTags`
- `Updating to latest 3.39`

Is this a known issue? I looked far into the land of contentful docs but can't find anything, I can only see the `getUsers`
Was wondering if there are way to reconfigure the limit.
 

Thanks a lot!

**Comment by shikaan** [comment]
Hello @mlawingco 

Thanks for your contribution! 

Unfortunately we do not plan to do further work on Space API as we are currently working on new features meant to supersede. A new big update will be soon released, so stay tuned ([here](https://github.com/contentful/contentful-management.js/pull/889) a small sneak peek)
