### ISSUE TITLE
Custom MultipleEntryReferenceEditor

### ISSUE THREAD

**Issue by fedorenkodev** [contentful/ui-extensions-sdk#900]
Hey guys, is it possible inside the entry editor to get all fields of a reference entry and render them right here [without another iframe](https://tppr.me/3S3Vq) + still have the CRUD functionality for a referenced entry? 

I have a model ["Module: Icon List"](https://tppr.me/cmFnN) which has 3 fields: title, content, options. Content and Options are reference fields. The Content field may include a batch of [other different models](https://tppr.me/QJY7f), e.g. ["Block: Icon"](https://tppr.me/U3a6H), "Block: Header" etc., Options field also may include [other models](https://tppr.me/gwfDH). 
I wanna render all fields of referenced entries with the ability to manipulate their data instead to have just a card that opens a reference entry in a new popup with a new iframe. As result, I need to get something like this https://tppr.me/Rv43b

I tried to work with the [MultipleEntryReferenceEditor](https://contentful-field-editors.netlify.app/reference-multiple) component and with its renderCustomCard property. In props of renderCustomCard, there is the 'entity.fields' property, but fields inside this don't have any methods, e.g. setValue(), getValue(), getForLocale(), etc. so it's just an object without any functionality. 

I will be grateful for any help.

**Comment by kdamball** [comment]
Closing this as response is in the [slack thread](https://contentful-community.slack.com/archives/CBR24P3T4/p1629371545088700?thread_ts=1628522882.021500&cid=CBR24P3T4)
