### ISSUE TITLE
Can't specify content-type to open with openEntriesList

### ISSUE THREAD

**Issue by petergray-maker** [contentful/ui-extensions-sdk#909]
Hello I'm using the App SDK and want to link from my app to a specified content type list
So went to use  `sdk.navigator.openEntriesList()`  but it doesn't allow you to specify a content type to list.

I would like to be able to specify the content-type that should be filtered in the content list page. Similar to how `sdk.navigator.openNewEntry('contentTypeID');`  functions.

**Comment by andipaetzold** [comment]
Hey @petergray-maker,

as you wrote correctly, this is currently not possible using the App SDK.
We currently do not plan to add this functionality to the App Framework but I noted your request internally and we might consider it for a future release.
