### ISSUE TITLE
Canary - cmaAdapter management client stopped working

### ISSUE THREAD

**Issue by jroehl** [contentful/ui-extensions-sdk#941]
Hey old colleagues,
hope you're doing great.

I was playing around with the new (canary) cmaAdapter (love this feature) - but suddenly today function calls are throwing an error `code: "TypeError" data: undefined message: "Cannot read property 'makeRequest' of undefined"`.

E.g.
```js
const cma = createClient(
        { apiAdapter: sdk.cmaAdapter },
        {
          type: 'plain',
          defaults: {
            environmentId: sdk.ids.environment,
            spaceId: sdk.ids.space,
          },
        }
      );
const result = await cma.asset.getMany({});
```

Can you help out with this? :pray:

**Comment by loweisz** [comment]
Hey @jroehl, 👋
Probably you are using an app in the field location, or is it somewhere else? 
We are in the process of fixing some issues that do not allow the cma adapter to work at this location. 
We are working hard to reintroduce it and it should be working again soon. 

If you want to keep playing around, you should be able to use it from all other locations

**Comment by jroehl** [comment]
Thanks for the quick reply @loweisz 
Yes, indeed - it's a `FieldExtension`. Could you please update here as well as soon as this is fixed?
Thanks a bunch 🙂

**Comment by shikaan** [comment]
Hey @jroehl,
Hope you're doing great :) You should be able to use the canary adapter on all the locations now. Can you confirm that?

Thanks a ton 🙇

**Comment by jroehl** [comment]
hey @shikaan, sorry for the late reply - it works like a charm (again)!
Thanks for the quick fix .. Best wishes to you and the team :)
