### ISSUE TITLE
How can I upload a file and create new assets?

### ISSUE THREAD

**Issue by jscasca** [contentful/ui-extensions-sdk#950]
Since the SDK doesn't have a `createAssetFromFile` the only option seems to be `createAsset`.  From the docs it seems that `createAsset` will need an upload reference. Unfortunately, the `createUpload` function only take the base64 string but does not return anything.

What's the correct way to upload and then create a new asset?

**Comment by shikaan** [comment]
Hello @jscasca,

As you can read [in this blog post](https://www.contentful.com/blog/2017/03/02/uploading-files-directly-to-contentful/) Upload API will return an `id` which you can then use to create a new Asset.

This is roughly an example of how you can do that using [App SDK](https://www.contentful.com/developers/docs/extensibility/app-framework/sdk/):

```js
const upload = await sdk.space.createUpload(base64Img)

const asset = await sdk.space.createAsset({
  fields: {
    title: {
      en: 'Puppy Pic'
    },
    file: {
      en: {
        contentType: 'image/png',
        fileName: 'my_puppy.png',
        uploadFrom: {
          sys: {
            type: "Link",
            linkType: "Upload",
            id: upload.sys.id
          }
        }
      }
    }
  }
})

await sdk.space.processAsset(asset, 'en')
```

You can proceed usual ways to then publish the Asset.

Have a great day,

**Comment by jscasca** [comment]
Hi @shikaan I haven't tried the code since TypeScript complains about the definition of that function. I'm using `@contentful/app-sdk@3.39.0` and the type definition is the following: `createUpload: (base64data: string) => void;`
I would expect for it to return a Promise like the rest of the functions (for example: `createAsset: <T = Object, InputArgs = any>(data: InputArgs) => Promise<T>;`, hence my confusion.

**Comment by shikaan** [comment]
Hello @jscasca 
The typing issue should be fixed in the PRs you see linked here.

Thanks for reporting and feel free to reopen should something be off

**Comment by jscasca** [comment]
Thanks, @shikaan . That's awesome!
