### ISSUE TITLE
Include defaultValue in field and contentType typings

### ISSUE THREAD

**Issue by AndrewLeedham** [contentful/ui-extensions-sdk#977]
Default values seems like they should be accessible in ui-extensions: https://www.contentful.com/developers/docs/references/content-management-api/#default-values

Seems like it should be part of this object: https://github.com/contentful/ui-extensions-sdk/blob/1dd863effbb3d47223eacaeb93a77d6e0de43a3b/lib/types.ts#L299

Perhaps it could be added here as well? https://github.com/contentful/ui-extensions-sdk/blob/1dd863effbb3d47223eacaeb93a77d6e0de43a3b/lib/types.ts#L149

**Comment by Jwhiles** [comment]
Hey Andrew, thanks for raising this issue. I've added it to our internal backlog. We'll update this ticket when there is more information to share.

**Comment by colomolo** [comment]
Hey @AndrewLeedham there are some changes happened with publishing of App SDK v4. `ContentTypeField` type moved to `contentful-management` repo [here](https://github.com/contentful/contentful-management.js/blob/master/lib/entities/content-type-fields.ts#L43-L54) and it already has `defaultValue` field.

**Comment by colomolo** [comment]
And I don't think we need to add `defaultValue` as a part of entry field API as this is a property of Content Type.
